name: hello2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on:
      - self-hosted
      - master
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Hello World!
